apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: kafka
    spec:
      containers:
      - env:
        - name: KAFKA_PORT
          value: "9092"
        image: lcampos01/practica_creativa_docker-kafka:latest
        name: kafka
        ports:
          - containerPort: 9092
            protocol: TCP
          - containerPort: 9093
            protocol: TCP
      restartPolicy: Always
