apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: spark-worker-2
  name: spark-worker-2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-worker-2
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: spark-worker-2
    spec:
      containers:
        - image: lcampos01/practica_creativa_docker-spark-worker:latest
          name: spark-worker-2
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
