apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: spark-submit
  name: spark-submit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-submit
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: spark-submit
    spec:
      containers:
        - image: lcampos01/practica_creativa_docker-k8s-spark-submit:latest
          name: spark-submit
          ports:
            - containerPort: 4040
              protocol: TCP
      restartPolicy: Always
